/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface PlataformaColeccionablesInterface extends ethers.utils.Interface {
  functions: {
    "coleccionablesERC1155()": FunctionFragment;
    "coleccionablesERC721()": FunctionFragment;
    "comprarColeccionableERC1155(uint256,uint256,uint256)": FunctionFragment;
    "comprarColeccionableERC721(uint256,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "tokenERC20()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transferirPropiedad(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "coleccionablesERC1155",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "coleccionablesERC721",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "comprarColeccionableERC1155",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "comprarColeccionableERC721",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenERC20",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferirPropiedad",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "coleccionablesERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "coleccionablesERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "comprarColeccionableERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "comprarColeccionableERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenERC20", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferirPropiedad",
    data: BytesLike
  ): Result;

  events: {
    "ColeccionableComprado(address,uint256,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ColeccionableComprado"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type ColeccionableCompradoEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber] & {
    comprador: string;
    tokenId: BigNumber;
    amount: BigNumber;
    precio: BigNumber;
  }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class PlataformaColeccionables extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PlataformaColeccionablesInterface;

  functions: {
    coleccionablesERC1155(overrides?: CallOverrides): Promise<[string]>;

    coleccionablesERC721(overrides?: CallOverrides): Promise<[string]>;

    comprarColeccionableERC1155(
      _id: BigNumberish,
      _amount: BigNumberish,
      _precio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    comprarColeccionableERC721(
      _tokenId: BigNumberish,
      _precio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokenERC20(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferirPropiedad(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  coleccionablesERC1155(overrides?: CallOverrides): Promise<string>;

  coleccionablesERC721(overrides?: CallOverrides): Promise<string>;

  comprarColeccionableERC1155(
    _id: BigNumberish,
    _amount: BigNumberish,
    _precio: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  comprarColeccionableERC721(
    _tokenId: BigNumberish,
    _precio: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokenERC20(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferirPropiedad(
    _newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    coleccionablesERC1155(overrides?: CallOverrides): Promise<string>;

    coleccionablesERC721(overrides?: CallOverrides): Promise<string>;

    comprarColeccionableERC1155(
      _id: BigNumberish,
      _amount: BigNumberish,
      _precio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    comprarColeccionableERC721(
      _tokenId: BigNumberish,
      _precio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    tokenERC20(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferirPropiedad(
      _newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ColeccionableComprado(address,uint256,uint256,uint256)"(
      comprador?: null,
      tokenId?: null,
      amount?: null,
      precio?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        comprador: string;
        tokenId: BigNumber;
        amount: BigNumber;
        precio: BigNumber;
      }
    >;

    ColeccionableComprado(
      comprador?: null,
      tokenId?: null,
      amount?: null,
      precio?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        comprador: string;
        tokenId: BigNumber;
        amount: BigNumber;
        precio: BigNumber;
      }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    coleccionablesERC1155(overrides?: CallOverrides): Promise<BigNumber>;

    coleccionablesERC721(overrides?: CallOverrides): Promise<BigNumber>;

    comprarColeccionableERC1155(
      _id: BigNumberish,
      _amount: BigNumberish,
      _precio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    comprarColeccionableERC721(
      _tokenId: BigNumberish,
      _precio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokenERC20(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferirPropiedad(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    coleccionablesERC1155(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    coleccionablesERC721(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    comprarColeccionableERC1155(
      _id: BigNumberish,
      _amount: BigNumberish,
      _precio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    comprarColeccionableERC721(
      _tokenId: BigNumberish,
      _precio: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokenERC20(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferirPropiedad(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
